### ISSUE TITLE
How to create an auto-generated test report pipeline for Robot Framework?

### ISSUE THREAD

**Issue by tpai** [tpai/tpai.github.io#115]
Generating test reports is time-consuming and a boring process, so I use several services of AWS to automate it.

Robot Framework is python-based and the environment of our QA is Python 2, therefore I choose `python:2-alpine` image of docker hub which size is small and no redundant dependencies.

Next, install the required tools, run tests and generate a report. Here I need to write a `buildspec.yml` for CodeBuild project.

```yml
version: 0.2
phases:
  install:
    commands:
      - python -V
      - pip install robotframework
      - pip install robotframework-appiumlibrary
      - pip install robotframework-selenium2library
      - pip install wiremock --user
      - pip install python-dateutil pytz pymysql framework
      - apk update
      # install chromedriver
      - apk add --no-cache chromium chromium-chromedriver
      # specify timezone to Asia/Taipei
      - apk add --no-cache tzdata
      - ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime
      - echo "Asia/Taipei" > /etc/timezone
  pre_build:
    commands:
      - pip show robotframework
      - chromium-browser --version
      - chromedriver --version
  build:
    commands:
      # in order to not block the pipeline process when test fail
      # add a pipe behind the test command and always return true
      - python -m robot -v from:aws -v env:beta testcases/ || true
      # collect test report assets
      - export FOLDER=$(date +%Y-%m-%d_%H:%M)
      - mkdir $FOLDER
      - mv log.html $FOLDER
      - mv report.html $FOLDER/index.html
      - mv *.png $FOLDER
artifacts:
  files:
    - '**/*.html'
    - '**/*.png'
  name: log-report
```

After CodeBuild finished tasks, it will output an artifact called `log-report`, this archived file will be forwarded to the next phase, and I set the action provider to `AWS S3` to extract the file to a bucket.

The file tree of the bucket will look like:

```
- yyyy-mm-dd_hh:mm/
- yyyy-mm-dd_hh:mm/
- yyyy-mm-dd_hh:mm/
```

S3 can not enable list objects as a static website so that I use Lambda Function to create an entrance for end users.

The last step is to create a CloudWatch rule to define a routine to trigger this pipeline when the time coming.
