### ISSUE TITLE
Can Dockerfile extends another one?

### ISSUE THREAD

**Issue by tpai** [tpai/tpai.github.io#76]
There's one better answer in Docker^17.05 - [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/).

That's say if you have one base image and another app image, basically there are two Dockerfile, by using multi-stage builds, you can prepending base image to app image and name **AS** different stage name, then specify the target stage in `docker-compose.yml`, see the following example:

`Dockerfile`

```dockerfile
FROM ubuntu:latest AS base-image
# commands of base image

FROM base-image AS app-image
# commands of app image
```

`docker-compose.yml`

```yml
version: '3.4'
services:
  web:
    build:
      context: .
      target: app-image
```

That's it! `docker-compose up` will do the rest.
