### ISSUE TITLE
How to access git private repo while building docker image?

### ISSUE THREAD

**Issue by tpai** [tpai/tpai.github.io#90]
1. `docker-compose`

    You can mount local ssh folder into container, the asymmetric key grant the access to container that it can access private repo.

    ```yaml
    version: '3.4'
    services:
      web:
        build:
          context: .
          target: my_app
        image: my_app
        volumes:
          - ~/.ssh:/root/.ssh
    ```

1. `docker build`

    First, pass build arg from command line.

    ```sh
    docker build --build-arg SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)" .
    ```

    Then the builder process will retrieve the arg and create asymmetric key with `RUN` command.

    ```dockerfile
    ARG SSH_PRIVATE_KEY
    RUN mkdir -p /root/.ssh/
    RUN echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa
    ```
